name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  go:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go:
          - '1.21'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5'
      - name: Build Perl for tests
        run: |
          cpanm -n Test::LongString
          pushd Perl/Encoder; perl Makefile.PL && make ; popd

      - name: Build and test
        run: export GO111MODULE=auto; ./travis/go.sh

  ruby:
    if: false # the 'ruby' job does not currently work
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby:
          - "1.9.3"
          - "2.0.0"
          - "2.1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: ruby -v

      - run: gem install rake-compiler
      - name: Build and test
        run: cd ruby && rake clean && rake && rake test

  java:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java:
          - "8"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5'
      - name: Build Perl for tests
        run: |
          cpanm -n Test::LongString
          pushd Perl/Encoder; perl Makefile.PL && make ; popd

      - name: Build and test
        run: ./travis/java.sh

  perl:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        perl:
          - "5.14"
          - "5.16"
          - "5.18"
          - "5.20"
          - "5.28"
          - "5.30"
          - "5.32"
          - "5.34"
          - "5.36"
        include:
          - { os: 'ubuntu-latest', perl: "5.34" , perl-threaded: true }
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          multi-thread: ${{ matrix.perl-threaded }}

      - run: perl -V

      - name: Build and test
        run: ./travis/perl.sh
